### PR TITLE
[08/08/2023] [02:04] Created a basic control display

### PR DESCRIPTION
**Pull request by Daniel-Zheleznov**
At the bottom of the screen I had made a place to display the controls for the gun, since previously it was confusing to know what to click to make the "weapon" work. I had also changed the default size to 1280x720 a more common aspect ratio.

### CODE REVIEW

**Review by farisfaikar — APPROVED** [review]
Wow ok, I didn't expect anyone to contribute to this project XD. The control panel looks fantastic. Also, I'm planning on refactoring the file structure a little bit. I'll merge this, Thanks!

**Comment by Daniel-Zheleznov** [comment]
I personally think that we can change the "weapon" to use config files, such as INI, JSON or smth else, and not python files to have multiple different guns such as a laser beam that takes longer to shoot, or a sniper or smth. But I also have a question, what is your plan with the project?

**Comment by farisfaikar** [comment]
I'm planning on making a top-down shooter game, kind of like [Running with Rifles](https://store.steampowered.com/app/270150/RUNNING_WITH_RIFLES/) and perhaps using pixel art like [Zero Seivert](https://store.steampowered.com/app/1782120/ZERO_Sievert/). The main focus would be the absurdly janky but technically accurate weapons handling, especially on the reload part. The weapons handling is inspired by [CM-SS13](https://cm-ss13.com/wiki/Main_Page). Checking a magazine will only tell you if it's full, half-full, a few bullets left, or empty and is shown either visually (if the magazine supports it) and/or using text. The magazine check mechanic is inspired by [Escape From Tarkov](https://www.escapefromtarkov.com/). I'm planning on making this game a zombie survival as well, maybe an arcade one, kind of like the flash game [Boxheads 2Play](https://www.twoplayergames.org/game/boxhead-2play). 

Also, there's going to be a sanity mechanic besides health which is inspired by [Don't Starve](https://store.steampowered.com/app/219740/Dont_Starve/). Oh yea, and both of them aren't shown so there's no convenient health bar or sanity bar. You're low on blood? Well, the screen around you is going to turn bloody. Low on sanity? If you're checking a magazine, instead of it being "half-full" it's going to say ["half-empty"](https://en.wikipedia.org/wiki/Is_the_glass_half_empty_or_half_full%3F), and if your sanity is low enough, might as well just say, "WE'RE ALL GOING TO DIE". 

In other games where you just hit R to reload and everything just works, in this game you have to do it all manually. 

What's that? You want to reload? 
> Well, remove the magazine first.

Where do you put the mag? 
> Choose one of the empty slots on your body armor. The UI for this is inspired by [Six Days in Fallujah](https://store.steampowered.com/app/1548850/Six_Days_in_Fallujah/)

It's full? 
> Well then just drop it on the ground. 

You've put the magazine back in the gun but it doesn't fire. 
> Well, you forgot to rack it, there's no bullet in the chamber.

Still nothing. 
> It's still on safe idiot. Change it to single-fire. 

*Click*. Nothing. 
> You just inserted an empty magazine, now you have to choose another one and start all over again, kinda. 

And so on and so forth. I might as well have to make a flowchart just to reload the damn gun XD.

The point is, reloading is now a skill-based mechanic. You don't just press reload, you have to do all of that just like a real gun would. It'll be hard to learn, hard to master. It will be especially challenging in a high-stress situation and it should be fun... well at least for machosists. It's janky, kind of like [Exanima](https://store.steampowered.com/app/362490/Exanima/) where you have to manually swing swords around like a drunken man. But when you get it, when you're skilled enough, it's rewarding to see you reload faster, perform actions faster, kill more efficiently, and so on. And the main focus shall then be the weapons handling, everything else will work. Doesn't even have to be a zombie game, it could be a battle royale, survival, or extraction-type game. But zombie survival is the easiest to go for at this time. This is probably quite a proposal for a game but if I have the time, energy, and motivation for it I might get serious with this project. Why is the game so weird and niche? Well, that's just my personal taste in games, I don't think this kind of game will appeal to people that much.

**Comment by Unbandit2006** [comment]
I really like it and I think it could eve go 3D given enough time. In the meantime pass discord so that we can talk without this old outdated GitHub system. From: Faris FaikarSent: Tuesday, August 8, 2023 22:18To: farisfaikar/UnserviceableCc: Daniel Zhelenzov; AuthorSubject: Re: [farisfaikar/Unserviceable] [08/08/2023] [02:04] Created a basic control display (PR #4) I'm planning on making a top-down shooter game, kind of like Running with Rifles and perhaps using pixel art like Zero Seivert. The main focus would be the absurdly janky but technically accurate weapons handling, especially on the reload part. The weapons handling is inspired by CM-SS13. Checking a magazine will only tell you if it's full, half-full, a few bullets left, or empty and is shown either visually (if the magazine supports it) and/or using text. The magazine check mechanic is inspired by Escape From Tarkov. I'm planning on making this game a zombie survival as well, maybe an arcade one, kind of like the flash game Boxheads 2Play.Also, there's going to be a sanity mechanic besides health which is inspired by Don't Starve. Oh yea, and both of them aren't shown so there's no convenient health bar or sanity bar. You're low on blood? Well, the screen around you is going to turn bloody. Low on sanity? If you're checking a magazine, instead of it being "half-full" it's going to say "half-empty", and if your sanity is low enough, might as well just say, "WE'RE ALL GOING TO DIE".In other games where you just hit R to reload and everything just works, in this game you have to do it all manually.What's that? You want to reload?Well, remove the magazine first.Where do you put the mag?Choose one of the empty slots on your body armor. The UI for this is inspired by Six Days in FallujahIt's full?Well then just drop it on the ground.You've put the magazine back in the gun but it doesn't fire.Well, you forgot to rack it, there's no bullet in the chamber.Still nothing.It's still on safe idiot. Change it to single-fire.Click. Nothing.You just inserted an empty magazine, now you have to choose another one and start all over again, kinda.And so on and so forth. I might as well have to make a flowchart just to reload the damn gun XD.The point is, reloading is now a skill-based mechanic. You don't just press reload, you have to do all of that just like a real gun would. It'll be hard to learn, hard to master. It will be especially challenging in a high-stress situation and it should be fun... well at least for machosists. It's janky, kind of like Exanima where you have to manually swing swords around like a drunken man. But when you get it, when you're skilled enough, it's rewarding to see you reload faster, perform actions faster, kill more efficiently, and so on. And the main focus shall then be the weapons handling, everything else will work. Doesn't even have to be a zombie game, it could be a battle royale, survival, or extraction-type game. But zombie survival is the easiest to go for at this time. This is probably quite a proposal for a game but if I have the time, energy, and motivation for it I might get serious with this project. Why is the game so weird and niche? Well, that's just my personal taste in games, I don't think this kind of game will appeal to people that much.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Daniel-Zheleznov** [comment]
I really like it and I think it could eve go 3D given enough time. In the meantime pass discord so that we can talk without this old outdated GitHub system.

**Comment by farisfaikar** [comment]
Welp, my discord username is farisfaikar

**Pull request merged**
